# Generated by Django 3.2.23 on 2023-11-29 10:51

import django.db.models.deletion
import dynamic_filenames
import simple_history.models
import stdimage.models
import stdimage.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                        ),
                        validators=[
                            stdimage.validators.MinSizeValidator(100, 100),
                            stdimage.validators.MaxSizeValidator(8000, 8000),
                        ],
                        variations={
                            "large": (600, 400),
                            "medium": (300, 200),
                            "thumbnail": (100, 100, True),
                        },
                    ),
                ),
                ("what", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=50)),
                ("extra_info", models.TextField(max_length=1000)),
                ("requested", models.DateField(auto_now_add=True)),
                ("duration", models.IntegerField(default=30, help_text="days")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("R", "Requested"),
                            ("AG", "Auto granted (<= month)"),
                            ("1st", "First extension"),
                            ("OK", "Approved"),
                            ("NO", "Denied"),
                            ("EX", "Expired"),
                            ("D", "Rescinded"),
                        ],
                        max_length=4,
                    ),
                ),
                ("lastdate", models.DateField(blank=True, null=True)),
                (
                    "extends",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.storage",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalStorage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            stdimage.validators.MinSizeValidator(100, 100),
                            stdimage.validators.MaxSizeValidator(8000, 8000),
                        ],
                    ),
                ),
                ("what", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=50)),
                ("extra_info", models.TextField(max_length=1000)),
                ("requested", models.DateField(blank=True, editable=False)),
                ("duration", models.IntegerField(default=30, help_text="days")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("R", "Requested"),
                            ("AG", "Auto granted (<= month)"),
                            ("1st", "First extension"),
                            ("OK", "Approved"),
                            ("NO", "Denied"),
                            ("EX", "Expired"),
                            ("D", "Rescinded"),
                        ],
                        max_length=4,
                    ),
                ),
                ("lastdate", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "extends",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="storage.storage",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical storage",
                "verbose_name_plural": "historical storages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
