repos:

  #####################
  ##  Generic hooks  ##
  #####################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
        exclude: spaceapi/templates/spaceapi.json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key

  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0  # Use the ref you want to point at
    hooks:
    -   id: check-untracked-migrations
    -   id: check-unapplied-migrations
    -   id: check-absent-migrations
    -   id: po-location-format
        # Mandatory, select one of the following options:
        # file: show only the file path as location
        # never: remove all locations
        args: ["--add-location", "file"]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      alias: autoformat

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        alias: autoformat
        args: [--fix]
      - id: ruff-format
