# Generated by Django 3.2.23 on 2023-11-29 10:51

from django.db import migrations, models

import mainssensor.hexfield


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mainssensor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    mainssensor.hexfield.HexField(
                        help_text="Unique tag id (4 digit hex)", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
