# Generated by Django 2.2.5 on 2020-01-18 14:37

from django.db import migrations
import mainssensor.hexfield


class Migration(migrations.Migration):

    dependencies = [
        ('mainssensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainssensor',
            name='tag',
            field=mainssensor.hexfield.HexField(help_text='Unique tag id (4 digit hex)', unique=True),
        ),
    ]
