# Generated by Django 4.2.21 on 2025-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="_enddatetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="agenda",
            name="_startdatetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="historicalagenda",
            name="_enddatetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="historicalagenda",
            name="_startdatetime",
            field=models.DateTimeField(null=True),
        ),
    ]
