# Generated by Django 4.2.21 on 2025-07-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0004_chore_wiki_url_historicalchore_wiki_url"),
        ("agenda", "0002_agenda__enddatetime_agenda__startdatetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="chore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chores.chore",
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalagenda",
            name="chore",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chores.chore",
            ),
        ),
        migrations.AddField(
            model_name="historicalagenda",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
