# Generated by Django 4.2.21 on 2025-07-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendachorestatuschange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='_enddatetime',
            new_name='enddatetime',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='_startdatetime',
            new_name='startdatetime',
        ),
        migrations.RenameField(
            model_name='historicalagenda',
            old_name='_enddatetime',
            new_name='enddatetime',
        ),
        migrations.RenameField(
            model_name='historicalagenda',
            old_name='_startdatetime',
            new_name='startdatetime',
        ),
    ]
