# Generated by Django 4.2.21 on 2025-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0005_rename__enddatetime_agenda_enddatetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("overdue", "Overdue"),
                    ("help_wanted", "Help Wanted"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agendachorestatuschange",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("overdue", "Overdue"),
                    ("help_wanted", "Help Wanted"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalagenda",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("overdue", "Overdue"),
                    ("help_wanted", "Help Wanted"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
