# Generated by Django 4.2.23 on 2025-10-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_agenda_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='occurrence_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_items', to='agenda.agenda'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='recurrences',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalagenda',
            name='occurrence_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalagenda',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda.agenda'),
        ),
        migrations.AddField(
            model_name='historicalagenda',
            name='recurrences',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
