# Generated by Django 4.2.23 on 2025-11-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0015_historicallocation_location_parent_and_more"),
        ("agenda", "0008_agenda_occurrence_date_agenda_recurrence_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acl.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalagenda",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="acl.location",
            ),
        ),
    ]
