# Generated by Django 2.2.5 on 2019-10-27 20:54

import jsonfield.fields
from django.db import migrations

import chores.models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="configuration",
            field=jsonfield.fields.JSONField(validators=[chores.models.validate_json]),
        ),
        migrations.AlterField(
            model_name="historicalchore",
            name="configuration",
            field=jsonfield.fields.JSONField(validators=[chores.models.validate_json]),
        ),
    ]
