# Generated by Django 3.2.18 on 2023-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0002_auto_20191027_2154"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalchore",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical chore",
                "verbose_name_plural": "historical chores",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalchorevolunteer",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical chore volunteer",
                "verbose_name_plural": "historical chore volunteers",
            },
        ),
        migrations.AlterField(
            model_name="historicalchore",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalchorevolunteer",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
