# Generated by Django 4.2.21 on 2025-07-11 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0004_chore_wiki_url_historicalchore_wiki_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('recipient_other', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chores.chore')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
