# Generated by Django 4.2.21 on 2025-07-13 11:31

from django.db import migrations, models

import chores.models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0005_chorenotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="configuration",
            field=models.JSONField(validators=[chores.models.validate_json]),
        ),
        migrations.AlterField(
            model_name="historicalchore",
            name="configuration",
            field=models.JSONField(validators=[chores.models.validate_json]),
        ),
    ]
