# Generated by Django 4.2.11 on 2024-10-04 19:59

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.models.validators
from django.conf import settings
from django.db import migrations, models

import pettycredit.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PettycreditClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settled",
                    models.BooleanField(
                        default=False,
                        help_text="Wether or not the claim has been settled already",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Date of the claim"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=pettycredit.models.claim_experiry_default,
                        help_text="Expiry date of the claim; when it gets auto charged/rolled up",
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro")],
                        default="EUR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="EUR",
                        max_digits=8,
                        null=True,
                        validators=[djmoney.models.validators.MinMoneyValidator(0)],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description / omschrijving van waarvoor deze betaling is",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "dst",
                    models.ForeignKey(
                        blank=True,
                        help_text="Whom to pay the money to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        blank=True,
                        help_text="Whom paid you",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isDeptor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PettycreditClaimChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date of the claim change",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Reason for the change",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "claim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pettycredit.pettycreditclaim",
                    ),
                ),
            ],
        ),
    ]
