# Generated by Django 4.2.8 on 2025-01-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0015_alter_pettycashbalancecache_owner'),
        ('pettycredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycreditclaim',
            name='settled_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pettycash.pettycashtransaction'),
        ),
    ]
