# Generated by Django 4.2.23 on 2025-10-11 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.models.validators
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminal', '0002_alter_historicalterminal_accepted_and_more'),
        ('pettycash', '0021_alter_historicalpettycashreimbursementrequest_src_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCheckout',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date of start of the transaction', null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', help_text='Amount shown on the display of the Sumup terminal', max_digits=8, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)])),
                ('client_transaction_id', models.CharField(blank=True, help_text='Client transaction ID as reported by SumUp during initial request to activate SOLO', max_length=48, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction reported back from Sumup after the payment completed on the SOLO terminal', max_length=48, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date of sumup callback', null=True)),
                ('debug_note', models.JSONField(blank=True, help_text='Additional information on SumUP state when applicable', max_length=512, null=True)),
                ('state', models.CharField(blank=True, choices=[('PREPARED', 'Prepared but not yet submitted to sumit'), ('SUBMITTED', 'Submitted to sumup; no callback yet'), ('SUCCESSFUL', 'Sumup reported the transaction as successful'), ('CANCELLED', 'Sumup reported the transaction as cancelled (usually by the end user'), ('FAILED', 'Sumup reported transaction failed'), ('PENDING', 'Sumup reported the transaction pending'), ('ERROR', 'Internal error or unknown state reported by Sumup')], default='PREPARED', max_length=16, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, help_text='Participants that pays into the pot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settled_tx', models.ForeignKey(blank=True, db_constraint=False, help_text='Actual settlement into the participants account (if any)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pettycash.pettycashtransaction')),
                ('terminal', models.ForeignKey(blank=True, db_constraint=False, help_text='Station/terminal used for this payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='terminal.terminal')),
            ],
            options={
                'verbose_name': 'historical checkout',
                'verbose_name_plural': 'historical checkouts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date of start of the transaction', null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', help_text='Amount shown on the display of the Sumup terminal', max_digits=8, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)])),
                ('client_transaction_id', models.CharField(blank=True, help_text='Client transaction ID as reported by SumUp during initial request to activate SOLO', max_length=48, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction reported back from Sumup after the payment completed on the SOLO terminal', max_length=48, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date of sumup callback', null=True)),
                ('debug_note', models.JSONField(blank=True, help_text='Additional information on SumUP state when applicable', max_length=512, null=True)),
                ('state', models.CharField(blank=True, choices=[('PREPARED', 'Prepared but not yet submitted to sumit'), ('SUBMITTED', 'Submitted to sumup; no callback yet'), ('SUCCESSFUL', 'Sumup reported the transaction as successful'), ('CANCELLED', 'Sumup reported the transaction as cancelled (usually by the end user'), ('FAILED', 'Sumup reported transaction failed'), ('PENDING', 'Sumup reported the transaction pending'), ('ERROR', 'Internal error or unknown state reported by Sumup')], default='PREPARED', max_length=16, null=True)),
                ('member', models.ForeignKey(blank=True, help_text='Participants that pays into the pot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isPaidBy', to=settings.AUTH_USER_MODEL)),
                ('settled_tx', models.ForeignKey(blank=True, help_text='Actual settlement into the participants account (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pettycash.pettycashtransaction')),
                ('terminal', models.ForeignKey(blank=True, help_text='Station/terminal used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paidOnStation', to='terminal.terminal')),
            ],
        ),
    ]
