# Generated by Django 4.2.23 on 2025-10-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pettycash",
            "0022_alter_historicalpettycashreimbursementrequest_src_and_more",
        ),
        ("sumup_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="fee_tx",
            field=models.ForeignKey(
                blank=True,
                help_text="Fee for this transaction (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feeFor",
                to="pettycash.pettycashtransaction",
            ),
        ),
        migrations.AddField(
            model_name="historicalcheckout",
            name="fee_tx",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Fee for this transaction (if any)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pettycash.pettycashtransaction",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="settled_tx",
            field=models.ForeignKey(
                blank=True,
                help_text="Actual settlement into the participants account (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="depositedBy",
                to="pettycash.pettycashtransaction",
            ),
        ),
    ]
