# Generated by Django 4.2.11 on 2024-03-21 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import motd.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=5000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('show_until', models.DateField(default=motd.models.get_deadline)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMotd',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=5000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('show_until', models.DateField(default=motd.models.get_deadline)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical motd',
                'verbose_name_plural': 'historical motds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
