# Generated by Django 4.2.11 on 2024-03-26 19:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmotd",
            name="date",
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
        migrations.AlterField(
            model_name="motd",
            name="date",
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
    ]
