# Generated by Django 4.2.11 on 2024-06-26 19:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name, initially as reported by the firmware. Potentially not unique!",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 fingerprint of the client certificate.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True,
                        help_text="256 bit nonce (as HEX)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time and date the device was last seen",
                        null=True,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Wether an administrator has checked the fingerprint against the display on the device and accepted it.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalTerminal",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name, initially as reported by the firmware. Potentially not unique!",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 fingerprint of the client certificate.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True,
                        help_text="256 bit nonce (as HEX)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Time and date the device was last seen",
                        null=True,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Wether an administrator has checked the fingerprint against the display on the device and accepted it.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical terminal",
                "verbose_name_plural": "historical terminals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
