# Generated by Django 4.2.11 on 2024-08-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalterminal",
            name="accepted",
            field=models.BooleanField(
                default=False,
                help_text="Wether an administrator has checked the fingerprint against the display on the device and accepted it manually; or implictly by swiping their tag at the actual device. Unsetting this flags blocks the terminal from interacting with teh payment and authorisation system. But will not wipe its (authorisation) cache.",
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="accepted",
            field=models.BooleanField(
                default=False,
                help_text="Wether an administrator has checked the fingerprint against the display on the device and accepted it manually; or implictly by swiping their tag at the actual device. Unsetting this flags blocks the terminal from interacting with teh payment and authorisation system. But will not wipe its (authorisation) cache.",
            ),
        ),
    ]
