# Generated by Django 3.2.23 on 2023-11-29 10:51

import django.db.models.deletion
import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("acl", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicelog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(max_length=16384)),
                (
                    "image",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        help_text="Upload an image; if relevant - optional. Fine to leave blank, upload later or post someting later to the mailing list",
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                        ),
                        validators=[
                            stdimage.validators.MinSizeValidator(100, 100),
                            stdimage.validators.MaxSizeValidator(8000, 8000),
                        ],
                        variations={
                            "large": (600, 400),
                            "medium": (300, 200),
                            "thumbnail": (100, 100, True),
                        },
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("FOUND_BROKEN", "I found it already in this state"),
                            (
                                "FOUND_FIX_BROKEN",
                                "I found it in this state, and fixed/cleaned it",
                            ),
                            (
                                "BROKEN",
                                "I accidentally broke it and need help fixing it",
                            ),
                            ("BROKEN_FIXED", "I accidentally broke it and fixed it"),
                            (
                                "OTHER",
                                "Other - describe the situation in the descrition field",
                            ),
                            ("FIXED", "Checked and put back in operation"),
                        ],
                        default="BROKEN",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acl.machine"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isReportedBy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
