# Generated by Django 3.2.18 on 2023-03-28 16:39

import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicelog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelog",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="Upload an image; if relevant - optional. Fine to leave blank, upload later or post someting later to the mailing list",
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
                variations={
                    "large": (600, 400),
                    "medium": (300, 200),
                    "thumbnail": (100, 100, True),
                },
            ),
        ),
    ]
