# Generated by Django 3.2.23 on 2023-11-29 10:51

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalMailinglist",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Short name; as for the '@' sign. E.g. 'spacelog'.",
                        max_length=40,
                    ),
                ),
                ("description", models.CharField(max_length=400)),
                (
                    "mandatory",
                    models.BooleanField(
                        default=False, help_text="Requires super admin to change"
                    ),
                ),
                (
                    "visible_months",
                    models.IntegerField(
                        default=0,
                        help_text="How long these archives are visible for normal members, or blank/0 if `forever'",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Show this in the normal (non admin) view",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mailinglist",
                "verbose_name_plural": "historical mailinglists",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSubscription",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Switch off to no longer receive mail from this list.",
                    ),
                ),
                (
                    "digest",
                    models.BooleanField(
                        default=False,
                        help_text="Receive all the mails of the day as one email; rather than throughout the day.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical subscription",
                "verbose_name_plural": "historical subscriptions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Mailinglist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name; as for the '@' sign. E.g. 'spacelog'.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=400)),
                (
                    "mandatory",
                    models.BooleanField(
                        default=False, help_text="Requires super admin to change"
                    ),
                ),
                (
                    "visible_months",
                    models.IntegerField(
                        default=0,
                        help_text="How long these archives are visible for normal members, or blank/0 if `forever'",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Show this in the normal (non admin) view",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Switch off to no longer receive mail from this list.",
                    ),
                ),
                (
                    "digest",
                    models.BooleanField(
                        default=False,
                        help_text="Receive all the mails of the day as one email; rather than throughout the day.",
                    ),
                ),
                (
                    "mailinglist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hasMember",
                        to="mailinglists.mailinglist",
                    ),
                ),
            ],
        ),
    ]
