# Generated by Django 2.1.5 on 2019-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailinglists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmailinglist",
            name="visible_months",
            field=models.IntegerField(
                default=0,
                help_text="How long these archives are visible for normal members, or blank/0 if `forever'",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="visible_months",
            field=models.IntegerField(
                default=0,
                help_text="How long these archives are visible for normal members, or blank/0 if `forever'",
            ),
        ),
    ]
