# Generated by Django 3.2.18 on 2023-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailinglists", "0002_auto_20190225_1433"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmailinglist",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical mailinglist",
                "verbose_name_plural": "historical mailinglists",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubscription",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical subscription",
                "verbose_name_plural": "historical subscriptions",
            },
        ),
        migrations.AddField(
            model_name="historicalmailinglist",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="Show this in the normal (non admin) view"
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="Show this in the normal (non admin) view"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmailinglist",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
