# Generated by Django 3.2.18 on 2023-03-28 16:39

import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberbox", "0003_auto_20190122_1657"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmemberbox",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical memberbox",
                "verbose_name_plural": "historical memberboxs",
            },
        ),
        migrations.AlterField(
            model_name="historicalmemberbox",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="memberbox",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="Optional - but highly recommened.",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
                variations={
                    "large": (600, 400),
                    "medium": (300, 200),
                    "thumbnail": (100, 100, True),
                },
            ),
        ),
    ]
