# Generated by Django 2.1.5 on 2019-01-19 20:13

import django.db.models.deletion
import dynamic_filenames
import simple_history.models
import stdimage.models
import stdimage.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUfo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        max_length=100,
                        validators=[
                            stdimage.validators.MinSizeValidator(100, 100),
                            stdimage.validators.MaxSizeValidator(8000, 8000),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNK", "Unidentified"),
                            ("OK", "Claimed"),
                            ("DEL", "can be disposed"),
                            ("DON", "Donated to the space"),
                        ],
                        default="UNK",
                        max_length=4,
                        null=True,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("dispose_by_date", models.DateField(blank=True, null=True)),
                ("lastChange", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ufo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Ufo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    stdimage.models.StdImageField(
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                        ),
                        validators=[
                            stdimage.validators.MinSizeValidator(100, 100),
                            stdimage.validators.MaxSizeValidator(8000, 8000),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNK", "Unidentified"),
                            ("OK", "Claimed"),
                            ("DEL", "can be disposed"),
                            ("DON", "Donated to the space"),
                        ],
                        default="UNK",
                        max_length=4,
                        null=True,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("dispose_by_date", models.DateField(blank=True, null=True)),
                ("lastChange", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
