# Generated by Django 2.1.5 on 2019-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalufo",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNK", "Unidentified"),
                    ("OK", "Claimed"),
                    ("DEL", "can be disposed"),
                    ("DON", "Donated to the space"),
                    ("GONE", "Gone"),
                ],
                default="UNK",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ufo",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNK", "Unidentified"),
                    ("OK", "Claimed"),
                    ("DEL", "can be disposed"),
                    ("DON", "Donated to the space"),
                    ("GONE", "Gone"),
                ],
                default="UNK",
                max_length=4,
                null=True,
            ),
        ),
    ]
