# Generated by Django 2.1.5 on 2019-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0003_auto_20190127_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmachine",
            name="out_of_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="machine",
            name="out_of_order",
            field=models.BooleanField(default=False),
        ),
    ]
