# Generated by Django 3.2.18 on 2023-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0007_alter_entitlement_issuer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalentitlement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical entitlement",
                "verbose_name_plural": "historical entitlements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallocation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical location",
                "verbose_name_plural": "historical locations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmachine",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical machine",
                "verbose_name_plural": "historical machines",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpermittype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical permit type",
                "verbose_name_plural": "historical permit types",
            },
        ),
        migrations.AlterField(
            model_name="historicalentitlement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallocation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmachine",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpermittype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
