# Generated by Django 4.2.8 on 2024-05-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0008_auto_20230328_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachine',
            name='category',
            field=models.CharField(choices=[('machine', 'Machine'), ('general_equipment', 'General equipment'), ('lights', 'Lights')], default='machine', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmachine',
            name='wiki_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalmachine',
            name='wiki_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(choices=[('machine', 'Machine'), ('general_equipment', 'General equipment'), ('lights', 'Lights')], default='machine', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='wiki_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='machine',
            name='wiki_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
