# Generated by Django 4.2.11 on 2024-08-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0009_historicalmachine_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time of the last change in the XS control system",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times something in the XS control ssytem changed",
                    ),
                ),
            ],
            options={
                "verbose_name": "ACL and XS change counter",
                "verbose_name_plural": "ACL and XS change counter",
            },
        ),
    ]
