# Generated by Django 4.2.8 on 2025-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0011_alter_location_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachine',
            name='do_not_show',
            field=models.BooleanField(default=False, help_text='Do not show this machine in CRM browse/listings (but it will be in API and other automatic lists). Useful for test machines or machines that are a hidden node of a larger machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='do_not_show',
            field=models.BooleanField(default=False, help_text='Do not show this machine in CRM browse/listings (but it will be in API and other automatic lists). Useful for test machines or machines that are a hidden node of a larger machine'),
        ),
    ]
