# Generated by Django 4.2.21 on 2025-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0012_historicalmachine_do_not_show_machine_do_not_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmachine",
            name="category",
            field=models.CharField(
                choices=[
                    ("machine", "Machine"),
                    ("general_equipment", "General equipment"),
                    ("software", "Software"),
                    ("lights", "Lights"),
                ],
                default="machine",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="category",
            field=models.CharField(
                choices=[
                    ("machine", "Machine"),
                    ("general_equipment", "General equipment"),
                    ("software", "Software"),
                    ("lights", "Lights"),
                ],
                default="machine",
                max_length=20,
            ),
        ),
    ]
