# Generated by Django 4.2.23 on 2025-11-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0014_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='location_parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acl.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='acl.location'),
        ),
    ]
