# Generated by Django 4.2.23 on 2025-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0015_historicallocation_location_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmachine",
            name="node_capability",
            field=models.CharField(
                choices=[(0, "Normal"), (1, "Login"), (2, "Logout")],
                default=0,
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="node_capability",
            field=models.CharField(
                choices=[(0, "Normal"), (1, "Login"), (2, "Logout")],
                default=0,
                max_length=1,
            ),
        ),
    ]
