# Generated by Django 4.2.23 on 2025-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0016_historicalmachine_node_capability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmachine",
            name="node_capability",
            field=models.IntegerField(
                choices=[(0, "Normal"), (1, "Login"), (2, "Logout")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="node_capability",
            field=models.IntegerField(
                choices=[(0, "Normal"), (1, "Login"), (2, "Logout")], default=0
            ),
        ),
    ]
