# Generated by Django 2.1.5 on 2019-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Optional; only visible to the trustees and board delegated administrators",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Optional; only visible to the trustees and board delegated administrators",
                max_length=40,
                null=True,
            ),
        ),
    ]
