# Generated by Django 2.1.5 on 2019-01-21 17:11

import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_auto_20190120_1615"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="image",
            field=models.TextField(
                blank=True,
                default="",
                max_length=100,
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                default="",
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
            ),
        ),
    ]
