# Generated by Django 2.1.4 on 2018-12-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20181207_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmember',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
