# Generated by Django 2.1.5 on 2019-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_auto_20190121_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltag",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="historicaltag",
            name="last_used",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="last_used",
            field=models.DateField(blank=True, null=True),
        ),
    ]
