# Generated by Django 2.1.5 on 2019-02-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_auto_20190206_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltag",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
