# Generated by Django 2.1.5 on 2019-02-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_auto_20190206_2133"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="telegram_user_id",
            field=models.CharField(
                blank=True,
                help_text="Optional; Telegram User ID; only visible to the trustees and board delegated administrators",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_user_id",
            field=models.CharField(
                blank=True,
                help_text="Optional; Telegram User ID; only visible to the trustees and board delegated administrators",
                max_length=200,
                null=True,
            ),
        ),
    ]
