# Generated by Django 2.1.5 on 2019-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_auto_20190210_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="uses_signal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="uses_signal",
            field=models.BooleanField(default=False),
        ),
    ]
