# Generated by Django 2.1.5 on 2019-02-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_auto_20190216_2308"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="always_uses_email",
            field=models.BooleanField(
                default=False,
                help_text="Receive notifications via email even when using a chat BOT",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="always_uses_email",
            field=models.BooleanField(
                default=False,
                help_text="Receive notifications via email even when using a chat BOT",
            ),
        ),
    ]
