# Generated by Django 3.2.7 on 2023-02-21 14:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_auto_20211001_1658"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBANSaltedHash",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valdigits",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(99),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("salt", models.BinaryField(max_length=32)),
                ("hash", models.BinaryField(max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Person likely assocated with this account",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
