# Generated by Django 3.2.18 on 2023-03-28 16:39

import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_ibansaltedhash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalauditrecord",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical audit record",
                "verbose_name_plural": "historical audit records",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltag",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterField(
            model_name="historicalauditrecord",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltag",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                default="",
                force_min_size=False,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
                variations={
                    "large": (600, 400),
                    "medium": (300, 200),
                    "thumbnail": (100, 100, True),
                },
            ),
        ),
    ]
