# Generated by Django 4.2.21 on 2025-07-18 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20230328_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagIsIssuedTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
