# Generated by Django 4.2.21 on 2025-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0015_alter_tag_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onsite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onsite_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
