# Generated by Django 4.2.23 on 2025-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_user_is_onsite_user_onsite_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["first_name", "last_name"],
                "permissions": [("wiki_account", "Has access to Wiki account")],
            },
        ),
    ]
