# Generated by Django 4.2.21 on 2025-07-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_user_is_onsite_user_onsite_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('wiki_account', 'Can have account with WikiMedia')]},
        ),
    ]
