# Generated by Django 4.2.23 on 2025-11-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0015_historicallocation_location_parent_and_more"),
        ("members", "0017_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="acl.location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="located_at",
                to="acl.location",
            ),
        ),
    ]
