name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.19
      - name: Setup python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Setup env
        run: |
          source .venv/bin/activate
          uv sync
      - name: Check migrations
        run: |
          uv run manage.py makemigrations --check --dry-run
      - name: Run tests
        run: |
          uv run python manage.py check
          uv run pytest --cov=.
