name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.19
      - name: Setup python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: |
          source .venv/bin/activate
          uv sync
          uv run python manage.py check
          uv pip install coverage
          uv run coverage run --source='.' manage.py test
      - name: Coverage report
        run: uv run coverage report
