name: Generate SBOM
on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC
  workflow_dispatch:  # Allow manual trigger
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.19

      - name: Setup python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Install cyclonedx-bom
        run: uv tool install cyclonedx-bom

      - name: Create SBOM directory
        run: mkdir -p ./.dist-info/sboms

      - name: Generate SBOM
        run: |
          source .venv/bin/activate
          cyclonedx-py environment "$(uv python find)" --spec-version 1.6 --output-reproducible > ./.dist-info/sboms/cyclonedx-1.6.json

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update SBOM"
          title: "chore(deps): Update SBOM"
          body: |
            Automated SBOM update generated by weekly workflow.

            - Updated dependency information in cyclonedx-1.6.json
            - Generated on: ${{ github.run_id }}
          branch: update-sbom-${{ github.run_number }}
          delete-branch: true
