# Generated by Django 2.2.5 on 2020-01-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfservice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwifinetwork",
            name="adminsonly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wifinetwork",
            name="adminsonly",
            field=models.BooleanField(default=False),
        ),
    ]
