# Generated by Django 3.2.18 on 2023-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfservice", "0002_auto_20200118_1537"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalwifinetwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical wi fi network",
                "verbose_name_plural": "historical wi fi networks",
            },
        ),
        migrations.AlterField(
            model_name="historicalwifinetwork",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
