# Generated by Django 3.2.7 on 2021-10-07 13:56

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pettycash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PettycashSku",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro")],
                        default="EUR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalpettycashbalancecache",
            name="last",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pettycash.pettycashtransaction",
                verbose_name="Last transaction that changed the balance",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of transaction"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="dst",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Paid to",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="src",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Paid by",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashbalancecache",
            name="last",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="pettycash.pettycashtransaction",
                verbose_name="Last transaction that changed the balance",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of transaction"
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="dst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isReceivedBy",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Paid to",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="src",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isSentBy",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Paid by",
            ),
        ),
    ]
