# Generated by Django 3.2.7 on 2021-10-11 19:47

import django.db.models.deletion
import djmoney.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl", "0006_auto_20201030_1054"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pettycash", "0002_auto_20211007_1556"),
    ]

    operations = [
        migrations.CreateModel(
            name="PettycashTerminal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name, initially as reported by the firmware. Potentially not unique!",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 fingerprint of the client certificate.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True,
                        help_text="256 bit nonce (as HEX)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time and date the device was last seen",
                        null=True,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Wether an administrator has checked the fingerprint against the display on the device and accepted it.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalpettycashbalancecache",
            name="last",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text="Last transaction that changed the balance",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pettycash.pettycashtransaction",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="date",
            field=models.DateTimeField(
                blank=True, help_text="Date of transaction", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="dst",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Paid to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="src",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Paid by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pettycashbalancecache",
            name="last",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Last transaction that changed the balance",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="pettycash.pettycashtransaction",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="date",
            field=models.DateTimeField(
                blank=True, help_text="Date of transaction", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="dst",
            field=models.ForeignKey(
                blank=True,
                help_text="Paid to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isReceivedBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="src",
            field=models.ForeignKey(
                blank=True,
                help_text="Paid by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isSentBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PettycashStation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "available_skus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SKUs avaialble at this terminal, when supported (or empty)",
                        related_name="availableSku",
                        to="pettycash.PettycashSku",
                    ),
                ),
                (
                    "default_sku",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default SKU (or the only one) at boot time and reverted to after 60 seconds",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defaultSku",
                        to="pettycash.pettycashsku",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminalIsLocated",
                        to="acl.location",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="station",
                        to="pettycash.pettycashterminal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPettycashTerminal",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name, initially as reported by the firmware. Potentially not unique!",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 fingerprint of the client certificate.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True,
                        help_text="256 bit nonce (as HEX)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Time and date the device was last seen",
                        null=True,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Wether an administrator has checked the fingerprint against the display on the device and accepted it.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pettycash terminal",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPettycashStation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "default_sku",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Default SKU (or the only one) at boot time and reverted to after 60 seconds",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pettycash.pettycashsku",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="acl.location",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pettycash.pettycashterminal",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pettycash station",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPettycashSku",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro")],
                        default="EUR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pettycash sku",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
