# Generated by Django 3.2.7 on 2021-11-02 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pettycash", "0004_auto_20211102_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpettycashreimbursementrequest",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date of expense"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashreimbursementrequest",
            name="submitted",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date the request was submitted",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date of expense"
            ),
        ),
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="submitted",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date the request was submitted",
            ),
        ),
    ]
