# Generated by Django 3.2.7 on 2022-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pettycash", "0008_alter_pettycashreimbursementrequest_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpettycashreimbursementrequest",
            name="isPayout",
            field=models.BooleanField(default=False, help_text="Internal hidden field"),
        ),
        migrations.AddField(
            model_name="pettycashreimbursementrequest",
            name="isPayout",
            field=models.BooleanField(default=False, help_text="Internal hidden field"),
        ),
    ]
