# Generated by Django 3.2.18 on 2023-03-28 16:39

import djmoney.models.fields
import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pettycash", "0009_auto_20221128_1709"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpettycashbalancecache",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pettycash balance cache",
                "verbose_name_plural": "historical pettycash balance caches",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpettycashreimbursementrequest",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pettycash reimbursement request",
                "verbose_name_plural": "historical pettycash reimbursement requests",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpettycashsku",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pettycash sku",
                "verbose_name_plural": "historical pettycash skus",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpettycashstation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pettycash station",
                "verbose_name_plural": "historical pettycash stations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpettycashterminal",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pettycash terminal",
                "verbose_name_plural": "historical pettycash terminals",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpettycashtransaction",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pettycash transaction",
                "verbose_name_plural": "historical pettycash transactions",
            },
        ),
        migrations.AlterField(
            model_name="historicalpettycashbalancecache",
            name="balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashbalancecache",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpettycashreimbursementrequest",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpettycashsku",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashsku",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpettycashstation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpettycashterminal",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashtransaction",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="pettycashbalancecache",
            name="balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="scan",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="Scan, photo or similar of the receipt",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
                variations={
                    "large": (600, 400),
                    "medium": (300, 200),
                    "thumbnail": (100, 100, True),
                },
            ),
        ),
        migrations.AlterField(
            model_name="pettycashsku",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pettycashtransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
