# Generated by Django 3.2.18 on 2023-10-09 11:05

from decimal import Decimal

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pettycash", "0010_auto_20230328_1839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpettycashreimbursementrequest",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="EUR",
                help_text="This system will only accept reimbursement up to 100.0. Above that; contact the trustees directly (hetbestuur@lists.makerspaceleiden.nl)",
                max_digits=8,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(0),
                    djmoney.models.validators.MaxMoneyValidator(Decimal("100.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashsku",
            name="description",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpettycashsku",
            name="name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="EUR",
                help_text="This system will only accept reimbursement up to 100.0. Above that; contact the trustees directly (hetbestuur@lists.makerspaceleiden.nl)",
                max_digits=8,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(0),
                    djmoney.models.validators.MaxMoneyValidator(Decimal("100.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pettycashsku",
            name="description",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="pettycashsku",
            name="name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
