# Generated by Django 4.2.11 on 2024-05-01 13:33

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pettycash", "0011_auto_20231009_1305"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpettycashreimbursementrequest",
            name="src",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                help_text="Party that pays (usually the Makerspace (de zwarte Pot))",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pettycashreimbursementrequest",
            name="src",
            field=models.ForeignKey(
                default=1,
                help_text="Party that pays (usually the Makerspace (de zwarte Pot))",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isReimbursedBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashreimbursementrequest",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="EUR", max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="EUR", max_digits=8
            ),
        ),
    ]
