# Generated by Django 4.2.8 on 2024-08-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("terminal", "0002_alter_historicalterminal_accepted_and_more"),
        ("pettycash", "0012_historicalpettycashreimbursementrequest_src_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpettycashbalancecache",
            name="last",
        ),
        migrations.RemoveField(
            model_name="pettycashbalancecache",
            name="last",
        ),
        migrations.AddField(
            model_name="historicalpettycashbalancecache",
            name="lasttxdate",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of most recent balance changing transaction (excluding any technical/system ones)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pettycashbalancecache",
            name="lasttxdate",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of most recent balance changing transaction (excluding any technical/system ones)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashreimbursementrequest",
            name="src",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=63,
                help_text="Party that pays (usually the Makerspace (de zwarte Pot))",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpettycashstation",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="terminal.terminal",
            ),
        ),
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="src",
            field=models.ForeignKey(
                default=63,
                help_text="Party that pays (usually the Makerspace (de zwarte Pot))",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isReimbursedBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pettycashstation",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="station",
                to="terminal.terminal",
            ),
        ),
    ]
