# Generated by Django 4.2.8 on 2024-08-22 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pettycash", "0013_remove_historicalpettycashbalancecache_last_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpettycashterminal",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="PettycashTerminal",
        ),
        migrations.DeleteModel(
            name="HistoricalPettycashTerminal",
        ),
    ]
