# Generated by Django 4.2.21 on 2025-07-21 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pettycash', '0015_alter_pettycashbalancecache_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpettycashreimbursementrequest',
            name='src',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, help_text='Party that pays (usually the Makerspace (de zwarte Pot))', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashreimbursementrequest',
            name='src',
            field=models.ForeignKey(default=3, help_text='Party that pays (usually the Makerspace (de zwarte Pot))', on_delete=django.db.models.deletion.CASCADE, related_name='isReimbursedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
