# Generated by Django 4.2.23 on 2025-07-27 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pettycash', '0018_alter_historicalpettycashreimbursementrequest_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpettycashreimbursementrequest',
            name='src',
            field=models.ForeignKey(blank=True, db_constraint=False, default=63, help_text='Party that pays (usually the Makerspace (de zwarte Pot))', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashreimbursementrequest',
            name='src',
            field=models.ForeignKey(default=63, help_text='Party that pays (usually the Makerspace (de zwarte Pot))', on_delete=django.db.models.deletion.CASCADE, related_name='isReimbursedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
