# Generated by Django 4.2.23 on 2025-11-21 11:41

import dynamic_filenames
import stdimage.models
import stdimage.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pettycash",
            "0022_alter_historicalpettycashreimbursementrequest_src_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pettycashreimbursementrequest",
            name="scan",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="Scan, photo or similar of the receipt",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                ),
                validators=[
                    stdimage.validators.MinSizeValidator(100, 100),
                    stdimage.validators.MaxSizeValidator(8000, 8000),
                ],
                variations={
                    "large": (1200, 1200),
                    "medium": (300, 200),
                    "thumbnail": (100, 100, True),
                },
            ),
        ),
    ]
